/*
 * Harness feature flag service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: ff@harness.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api
// HealthResponse struct for HealthResponse
type HealthResponse struct {
	Healthy bool `json:"healthy,omitempty"`
}
