/*
 * Harness feature flag service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: ff@harness.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api
// Error struct for Error
type Error struct {
	Code string `json:"code"`
	Message string `json:"message"`
}
