/*
 * Harness feature flag service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: ff@harness.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api
// FeatureFlag struct for FeatureFlag
type FeatureFlag struct {
	Key string `json:"key"`
	State FeatureFlagState `json:"state,omitempty"`
	Kind string `json:"kind"`
	Variations []Variation `json:"variations"`
	Tags []Tag `json:"tags,omitempty"`
}
