/*
 * Harness feature flag service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: ff@harness.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api
// FeatureFlagState the model 'FeatureFlagState'
type FeatureFlagState string

// List of FeatureFlagState
const (
	ON FeatureFlagState = "on"
	OFF FeatureFlagState = "off"
	ARCHIVED FeatureFlagState = "archived"
)
