/*
 * Harness feature flag service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: ff@harness.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api
// Clause struct for Clause
type Clause struct {
	Attribute string `json:"attribute,omitempty"`
	Op string `json:"op,omitempty"`
	Values []map[string]interface{} `json:"values,omitempty"`
	Negate bool `json:"negate,omitempty"`
}
