/*
 * Harness feature flag service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: ff@harness.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api
// TargetSegment struct for TargetSegment
type TargetSegment struct {
	// Unique identifier for the target segment.
	Key string `json:"key"`
	// Name of the target segment.
	Name string `json:"name"`
	Tags []Tag `json:"tags,omitempty"`
	Included []string `json:"included,omitempty"`
	Excluded []string `json:"excluded,omitempty"`
	// An array of rules that can cause a user to be included in this segment.
	Rules []Clause `json:"rules,omitempty"`
}
