/*
 * Harness feature flag service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Contact: ff@harness.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package api
// Target struct for Target
type Target struct {
	Key string `json:"key,omitempty"`
	Ip string `json:"ip,omitempty"`
	Country string `json:"country,omitempty"`
	Email string `json:"email,omitempty"`
	FirstName string `json:"firstName,omitempty"`
	LastName string `json:"lastName,omitempty"`
	Name string `json:"name,omitempty"`
	Anonymous bool `json:"anonymous,omitempty"`
	Custom map[string]interface{} `json:"custom,omitempty"`
}
